POST http://localhost:3333/api/v0/user/create
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "janedoe@gmail.com",
  "password": "password"
}

###

GET  http://localhost:3333/api/v0/user